<a href="https://colab.research.google.com/github/maSZiej/data-ds/blob/main/01_wprowadzenie/01_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [10]:
x=np.array([1,3])
print(x)
type(x)

[1 3]


numpy.ndarray

In [13]:
x=np.array([1.2,3.7,4.8])
x

array([1.2, 3.7, 4.8])

In [15]:
x.dtype

dtype('float64')

In [17]:
np.zeros(shape=(4,10),dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
np.ones(shape=(5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.full(shape=(3,3),fill_value=4,dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [23]:
np.arange(start=10,stop=100,step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

np.dot to mnożenie macierzy
